server:
  port: 8199
  
springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true
spring:
  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}
    bootstrap-servers: localhost:9092
    
  application:
    name: api-transaction-bff

  redis:
    port: 6379
    host: localhost
    timeout: 5000
app:
  topic: transaction

limites:
  url: http://localhost:8299/limite-diario
  
transaction:
  url: http://localhost:8399/transaction