version: '3.4'

services:
  mysql:
    container_name: mysql-container
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: limite
      MYSQL_PASSWORD: limite_passwd
      MYSQL_DATABASE: limites
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3399
    ports:
      - 3399:3399
    expose:
      - 3399
    networks:
      - mysql
networks:
  mysql:
    driver: bridge 
